FROM --platform=$BUILDPLATFORM golang:1.19 AS builder

WORKDIR /go/app

COPY . .

ARG TARGETOS TARGETARCH

RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    CGO_ENABLED=0 make mysqlscepserver-$TARGETOS-$TARGETARCH

FROM gcr.io/distroless/static

ARG TARGETOS TARGETARCH

COPY --from=builder /go/app/mysqlscepserver-$TARGETOS-$TARGETARCH /app/mysqlscepserver

EXPOSE 8080

WORKDIR /app

ENTRYPOINT ["/app/mysqlscepserver"]
