name: Issue
description: Project issue form.
body:
  - type: markdown
    attributes:
      value: |
        GitHub issues are not for support questions.
  - type: input
    id: version
    attributes:
      label: Version in use
      description: Version of the software that you're using.
      placeholder: v1.13.0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what happened.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output from the server or devices. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: support
    attributes:
      label: Maintenance mode
      description: This project is [in maintenance mode](https://micromdm.io/blog/micromdm-v1-maintenance-mode/) and has limited support.
      options:
        - label: I understand this project is in maintenance mode and has limited support.
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/micromdm/micromdm/blob/main/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
