body:
  - type: markdown
    attributes:
      value: |
        GitHub issues are not for support questions.
  - type: checkboxes
    id: terms
    attributes:
      label: Maintenance mode
      description: This project is in maintenance mode and has limited support.
      options:
        - label: I understand this project is in maintenance mode and has limited support.
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/micromdm/micromdm/blob/main/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
