on:
  release:
    types: [published]
jobs:
  release-zips:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3.6.0
        with:
          fetch-depth: 0

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe  # v4.1.0
        with:
          go-version: '1.19.x'

      - run: CGO_ENABLED=0 make release

      - run: gh release upload ${{ github.event.release.tag_name }} *.zip
        env:
            GH_TOKEN: ${{ github.token }}
